<x-guest-layout>
    <section x-data="{ images: [], active: 0, open(images) { this.images = images; this.active = 0; document.body.classList.add('overflow-hidden') }, close() { this.images = []; document.body.classList.remove('overflow-hidden') }, previous() { this.active = (this.active + this.images.length - 1) % this.images.length }, next() { this.active = (this.active + 1) % this.images.length } }" @keydown.escape.window="close()" class="bg-slate-50">
        <div class="bg-[#161b48e6] px-4 pb-14 pt-10 text-white sm:px-6 sm:pb-20 sm:pt-14 lg:px-8">
            <div class="mx-auto max-w-7xl"><p class="text-sm font-semibold uppercase tracking-[0.24em] text-amber-300">Meetings & events</p><div class="mt-3 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div class="max-w-2xl"><h1 class="text-3xl font-bold tracking-tight sm:text-5xl">Conference spaces that work around your event.</h1><p class="mt-4 text-sm leading-6 text-slate-200 sm:text-base">Choose a flexible setting for team meetings, workshops, private events, and celebrations.</p></div><p class="rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-sm text-slate-100">{{ $rooms->count() }} space{{ $rooms->count() === 1 ? '' : 's' }} available</p></div></div>
        </div>

        <div class="mx-auto -mt-6 max-w-7xl px-4 pb-10 sm:px-6 sm:pb-14 lg:px-8">
            <div class="grid gap-5 sm:grid-cols-2 md:grid-cols-3">
                @forelse ($rooms as $room)
                    <article class="flex h-full flex-col overflow-hidden rounded-2xl bg-white shadow-xl shadow-slate-300/40 ring-1 ring-slate-900/5">
                        <div class="relative">
                            @php($imageUrl = $room->image && \Illuminate\Support\Facades\Storage::disk('public')->exists($room->image) ? \Illuminate\Support\Facades\Storage::disk('public')->url($room->image) : null)
                            @if ($imageUrl)<img src="{{ $imageUrl }}" alt="{{ $room->name }}" class="h-48 w-full object-cover sm:h-52">@else<div class="flex h-48 items-center justify-center bg-gradient-to-br from-slate-100 to-slate-200 text-sm font-semibold text-slate-500 sm:h-52">Conference room image coming soon</div>@endif
                            <span class="absolute left-4 top-4 rounded-full bg-white/95 px-3 py-1 text-xs font-bold text-slate-800 shadow-sm">Up to {{ $room->capacity }} guests</span>
                        </div>
                        <div class="flex flex-1 flex-col p-5"><h2 class="text-xl font-bold text-slate-900">{{ $room->name }}</h2><p class="mt-2 line-clamp-3 text-sm leading-6 text-slate-600">{{ $room->description }}</p>
                            <div class="mt-4 flex flex-wrap gap-2">@forelse ($room->facilities->take(4) as $facility)<span class="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">{{ $facility->name }}</span>@empty<span class="text-sm text-slate-500">Flexible event setup</span>@endforelse</div>
                            <div class="mt-5 border-t border-slate-100 pt-4"><p class="text-xs font-semibold uppercase tracking-wide text-slate-500">Hourly rate</p><p class="mt-1 text-xl font-bold text-slate-900">GHS {{ number_format($room->price_per_hour, 2) }} <span class="text-sm font-normal text-slate-500">/ hour</span></p></div>
                            <div class="mt-auto grid gap-3 pt-5 {{ filled($room->gallery) ? 'sm:grid-cols-2' : '' }}"><a href="{{ route('conference.book', $room->id) }}" class="flex min-h-12 w-full items-center justify-center rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white transition hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2">Book this room</a>@if (filled($room->gallery))<button type="button" @click="open(@js(collect($room->gallery)->map(fn ($image) => asset('storage/' . $image))->values()))" class="flex min-h-12 w-full items-center justify-center rounded-xl bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-800 transition hover:bg-amber-100 focus:outline-none focus:ring-2 focus:ring-amber-500 focus:ring-offset-2">View gallery</button>@endif</div>
                        </div>
                    </article>
                @empty
                    <div class="rounded-2xl bg-white p-8 text-center text-slate-600 shadow-sm sm:col-span-2 md:col-span-3"><h2 class="text-xl font-bold text-slate-900">No conference rooms are available right now.</h2><p class="mt-2 text-sm">Please check back shortly or contact us for help planning your event.</p><a href="{{ route('contact') }}" class="mt-5 inline-flex min-h-11 items-center justify-center rounded-xl bg-blue-600 px-5 py-2 text-sm font-semibold text-white">Contact us</a></div>
                @endforelse
            </div>
        </div>

        <div x-show="images.length" x-cloak x-transition.opacity class="fixed inset-0 z-[100] flex items-center justify-center bg-black/90 p-4 sm:p-8" role="dialog" aria-modal="true" @click.self="close()"><button type="button" @click="close()" class="absolute right-4 top-4 flex h-11 w-11 items-center justify-center rounded-full bg-white/10 text-3xl text-white hover:bg-white/20" aria-label="Close gallery">&times;</button><button type="button" x-show="images.length > 1" @click="previous()" class="absolute left-3 flex h-11 w-11 items-center justify-center rounded-full bg-white/10 text-2xl text-white hover:bg-white/20 sm:left-8" aria-label="Previous image">&lsaquo;</button><img :src="images[active]" alt="Conference room gallery image" class="max-h-[78vh] max-w-full rounded-xl object-contain shadow-2xl"><button type="button" x-show="images.length > 1" @click="next()" class="absolute right-3 flex h-11 w-11 items-center justify-center rounded-full bg-white/10 text-2xl text-white hover:bg-white/20 sm:right-8" aria-label="Next image">&rsaquo;</button><div class="absolute bottom-5 flex max-w-[90vw] gap-2 overflow-x-auto"><template x-for="(image, index) in images" :key="image"><button type="button" @click="active = index" class="h-14 w-16 shrink-0 overflow-hidden rounded-lg ring-2" :class="active === index ? 'ring-white' : 'ring-transparent'"><img :src="image" alt="" class="h-full w-full object-cover"></button></template></div></div>
    </section>
</x-guest-layout>
