<x-guest-layout>
    <section x-data="{ images: [], active: 0, open(images) { this.images = images; this.active = 0; document.body.classList.add('overflow-hidden') }, close() { this.images = []; document.body.classList.remove('overflow-hidden') }, previous() { this.active = (this.active + this.images.length - 1) % this.images.length }, next() { this.active = (this.active + 1) % this.images.length } }" @keydown.escape.window="close()" class="bg-slate-50">
        <div class="bg-[#161b48e6] px-4 pb-14 pt-10 text-white sm:px-6 sm:pb-20 sm:pt-14 lg:px-8"><div class="mx-auto max-w-7xl"><p class="text-sm font-semibold uppercase tracking-[0.24em] text-amber-300">Stay with us</p><div class="mt-3 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div class="max-w-2xl"><h1 class="text-3xl font-bold tracking-tight sm:text-5xl">Find the room that fits your stay.</h1><p class="mt-4 text-sm leading-6 text-slate-200 sm:text-base">Explore comfortable room types with thoughtful amenities for business trips, holidays, and everything in between.</p></div><p class="rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-sm text-slate-100">{{ $roomTypes->count() }} room type{{ $roomTypes->count() === 1 ? '' : 's' }} to explore</p></div></div></div>

        <div class="mx-auto -mt-6 max-w-7xl px-4 pb-10 sm:px-6 sm:pb-14 lg:px-8"><div class="grid gap-5 sm:grid-cols-2 md:grid-cols-3">
            @forelse ($roomTypes as $roomType)
                <article class="flex h-full flex-col overflow-hidden rounded-2xl bg-white shadow-xl shadow-slate-300/40 ring-1 ring-slate-900/5">
                    <div class="relative">@if ($roomType->image)<img src="{{ asset('storage/' . $roomType->image) }}" alt="{{ $roomType->name }}" class="h-48 w-full object-cover sm:h-52">@else<div class="flex h-48 items-center justify-center bg-gradient-to-br from-slate-100 to-slate-200 text-sm font-semibold text-slate-500 sm:h-52">Room image</div>@endif@if ($roomType->capacity)<span class="absolute left-4 top-4 rounded-full bg-white/95 px-3 py-1 text-xs font-bold text-slate-800 shadow-sm">Up to {{ $roomType->capacity }} guests</span>@endif</div>
                    <div class="flex flex-1 flex-col p-5"><h2 class="text-xl font-bold text-slate-900">{{ $roomType->name }}</h2><p class="mt-2 line-clamp-3 text-sm leading-6 text-slate-600">{{ $roomType->description }}</p><div class="mt-4 flex flex-wrap gap-2">@forelse ($roomType->facilities->take(4) as $facility)<span class="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">{{ $facility->name }}</span>@empty<span class="text-sm text-slate-500">Comfortable hotel stay</span>@endforelse</div><div class="mt-5 border-t border-slate-100 pt-4"><p class="text-xs font-semibold uppercase tracking-wide text-slate-500">Nightly rate</p><p class="mt-1 text-xl font-bold text-slate-900">GHS {{ number_format($roomType->price_per_night ?? 0, 2) }} <span class="text-sm font-normal text-slate-500">/ night</span></p></div>
                        @if (filled($roomType->gallery))
                            <div class="mt-auto grid gap-3 pt-5 sm:grid-cols-3"><a href="{{ route('rooms.available', $roomType->id) }}" class="flex min-h-12 items-center justify-center rounded-xl bg-blue-600 px-3 py-3 text-sm font-semibold text-white transition hover:bg-blue-700">View rooms</a><a href="{{ route('rooms.calendar', $roomType->id) }}" class="flex min-h-12 items-center justify-center rounded-xl bg-slate-100 px-3 py-3 text-sm font-semibold text-slate-700 transition hover:bg-slate-200">Availability</a><button type="button" @click="open(@js(collect($roomType->gallery)->map(fn ($image) => asset('storage/' . $image))->values()))" class="flex min-h-12 items-center justify-center rounded-xl bg-amber-50 px-3 py-3 text-sm font-semibold text-amber-800 transition hover:bg-amber-100">Gallery</button></div>
                        @else
                            <div class="mt-auto grid gap-3 pt-5 sm:grid-cols-2"><a href="{{ route('rooms.available', $roomType->id) }}" class="flex min-h-12 items-center justify-center rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white transition hover:bg-blue-700">View rooms</a><a href="{{ route('rooms.calendar', $roomType->id) }}" class="flex min-h-12 items-center justify-center rounded-xl bg-slate-100 px-4 py-3 text-sm font-semibold text-slate-700 transition hover:bg-slate-200">Availability</a></div>
                        @endif
                    </div>
                </article>
            @empty
                <div class="rounded-2xl bg-white p-8 text-center text-slate-600 shadow-sm sm:col-span-2 md:col-span-3"><h2 class="text-xl font-bold text-slate-900">No room types are available right now.</h2><p class="mt-2 text-sm">Please check back shortly or contact us for help finding a stay.</p><a href="{{ route('contact') }}" class="mt-5 inline-flex min-h-11 items-center justify-center rounded-xl bg-blue-600 px-5 py-2 text-sm font-semibold text-white">Contact us</a></div>
            @endforelse
        </div></div>

        <div x-show="images.length" x-cloak x-transition.opacity class="fixed inset-0 z-[100] flex items-center justify-center bg-black/90 p-4 sm:p-8" role="dialog" aria-modal="true" @click.self="close()"><button type="button" @click="close()" class="absolute right-4 top-4 flex h-11 w-11 items-center justify-center rounded-full bg-white/10 text-3xl text-white hover:bg-white/20" aria-label="Close gallery">&times;</button><button type="button" x-show="images.length > 1" @click="previous()" class="absolute left-3 flex h-11 w-11 items-center justify-center rounded-full bg-white/10 text-2xl text-white hover:bg-white/20 sm:left-8" aria-label="Previous image">&lsaquo;</button><img :src="images[active]" alt="Room gallery image" class="max-h-[78vh] max-w-full rounded-xl object-contain shadow-2xl"><button type="button" x-show="images.length > 1" @click="next()" class="absolute right-3 flex h-11 w-11 items-center justify-center rounded-full bg-white/10 text-2xl text-white hover:bg-white/20 sm:right-8" aria-label="Next image">&rsaquo;</button><div class="absolute bottom-5 flex max-w-[90vw] gap-2 overflow-x-auto"><template x-for="(image, index) in images" :key="image"><button type="button" @click="active = index" class="h-14 w-16 shrink-0 overflow-hidden rounded-lg ring-2" :class="active === index ? 'ring-white' : 'ring-transparent'"><img :src="image" alt="" class="h-full w-full object-cover"></button></template></div></div>
    </section>
</x-guest-layout>
